/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'root' at '16/12/19 10:54' with Gradle 2.4
 *
 * @author root, @date 16/12/19 10:54
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
